# Elasticsearch with the Kibana Workflows connector baked in.
#   docker build -f docker/Dockerfile -t elasticsearch-esql-workflow:9.5.4 .
ARG STACK_VERSION=9.5.4
FROM docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
ARG STACK_VERSION
COPY --chown=elasticsearch:root dist/esql-datasource-workflow-*-es${STACK_VERSION}.zip /tmp/esql-datasource-workflow.zip
RUN bin/elasticsearch-plugin install --batch file:///tmp/esql-datasource-workflow.zip \
    && rm /tmp/esql-datasource-workflow.zip
